${XHOME}20-scfb.conf 'Section "Device"\n\t\tIdentifier "Card0"\n\t\tDriver "scfb"\nEndSection\n'
${XHOME}10-monitor.conf 'Section "Screen"\n\t\tIdentifier "Screen0"\n\t\tDevice "Card0"\n\t\tSubSection "Display"\n\t\tModes "1900x1200"\n\t\tEndSubSection\nEndSection\n'
${XHOME}00-keyboard.conf 'Section "InputClass"\n\t\tIdentifier "Keyboard1"\n\t\tMatchIsKeyboard "on"\n\t\tOption "XkbLayout" "de"\n\t\tOption "XkbModel" "pc104"\n\t\tOption "XkbVariant" ",qwertz"\n\t\tOption "XkbOptions" "grp:win_space_toggle"\nEndSection\n'
${XHOME}90-fonts.conf 'Section "Module"\n\t\tLoad "freetype"\nEndSection\n'

